services:
    response_service:
        class: Idchlife\DoctrineJSBundle\Service\ResponseService\ResponseService
        calls:
            - [setSerializer, ['@serializer']]

    repository_service:
        class: Idchlife\DoctrineJSBundle\Service\RepositoryService\RepositoryService
